"""Initial migration

Revision ID: 7627247f123a
Revises: 
Create Date: 2025-01-02 16:15:22.023871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7627247f123a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('signup_date')

    # ### end Alembic commands ###
