name: Playwright Test Runner

on:
  pull_request:
    branches:
      - main  # Run tests on pull requests to master
      - feature  # Run tests on pull requests to feature branch

jobs:
  test:
    runs-on: windows-latest  # Using Windows as per your specification

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify your Python version

    - name: Cache Python dependencies
      id: cache-deps  # Adding an ID to reference in later steps
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip  # Corrected path for Windows
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'  # Only run installation if cache was not hit
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        pip install flask
        pip install Flask-Mail
        pip install Flask-Migrate
        pip install playwright pytest
        playwright install

    - name: Run application
      run: python app.py 
    
    - name: Run tests
      run: pytest my_playwright_tests/tests/

    - name: Upload Screenshots (if tests fail)
      uses: actions/upload-artifact@v3
      if: failure()  # This step will run only if the previous step (Run tests) fails
      with:
        name: screenshots
        path: tests/screenshots/  # Adjust this path to where your screenshots are saved
